[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Esta regra cria a PONTE DE SEGURANÇA entre seu site e o Google
# Ela redireciona as chamadas de autenticação do seu domínio Netlify para o Firebase
[[redirects]]
  from = "/__/auth/*"
  to = "https://studio-9995869127-3ea67.firebaseapp.com/__/auth/:splat"
  status = 200
  force = true
