
[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Proxy para o Firebase Auth funcionar no domínio da Netlify
[[redirects]]
  from = "/__/auth/*"
  to = "https://studio-9995869127-3ea67.firebaseapp.com/__/auth/:splat"
  status = 200
  force = true

# Fallback para SPA routes se necessário
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  condition = "Role = admin" # Apenas um exemplo, remova se causar problemas
